version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
      #container_name: postgres
    env_file: .env
    hostname: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - portfolio-network
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-U", "postgres"]
      interval: 1s
      timeout: 10s
      retries: 3
  spider:
    image: ghcr.io/t0ha/midas-spiders:latest
      #container_name: postgres
    env_file: .env
    hostname: spider
    depends_on:
      postgres:
        condition: service_healthy
      #volumes:
      #  - ./python:/opt
    networks:
      - portfolio-network
  web:
    image: ghcr.io/t0ha/midas-web:latest
      #container_name: postgres
    env_file: .env
    hostname: web
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 127.0.0.1:4000:4000
      #volumes:
      #  - ./python:/opt
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
