name: Build Docker Image
on:
  push:
    branches:
      - master
    paths:
      - python/*

defaults:
  run:
    shell: bash
    
jobs:
  # tests:
  #   name: Run code checks and tests
  #   uses: ./.github/workflows/code-checks.yml
  #   secrets: inherit
        
  build_docker_image:
    name: Build Image
    runs-on: ubuntu-18.04
      #needs: [tests]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
          # with:
          #   submodules: recursive
          #   token: ${{ secrets.SUBMODULES_PAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Building and publishing an image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ./python
          tags: ghcr.io/t0ha/midas-spiders:latest
