name: Deploy Test
on:
  push:
    branches:
      - 1main
        # paths:
        #   - python/*
        #   - web/*
        #   - web/**/*

defaults:
  run:
    shell: bash
    
jobs:
  deploy_docker_imag:
    name: Deploy Image
    runs-on: ubuntu-20.04
    steps:
      - run: |
          echo "${{ vars.DO_HOST }}"

      - name: Deploy to test
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ vars.DO_HOST }}
          user: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          connect_timeout: 10s
          first_ssh: |
            cd ~/projects/midas
            docker compose pull
            docker compose up --build -d
